### ISSUE TITLE
Process flow not reliable with _blocker_ and _block:xyz_

### ISSUE THREAD

**Issue by flawseeker** [codingo/Interlace#103]
**Description:**

On latest version, processes seem to not execute in the expected order, i.e. not in sequence, when using _blocker_ and _block:xyz_ in command files.

**Steps to reproduce:**
1/ install latest version
2/ use the attached file as the command file, then run
[interlace_tests10.txt](https://github.com/codingo/Interlace/files/4803385/interlace_tests10.txt)
`interlace -t 10.10.10.1-9 -cL interlace_tests10.txt -threads 10`
FWIW I ran it on latest Kali inside a VM. I think it shouldn't matter, but I'm waiting to see if others have similar troubles.

**Expected behaviour:**
When doing for any 10.10.10.1-9 IP
`grep "10\.10\.10\.1" tests1.txt`
We should see IP followed by number 1 to 10 in order.

**Results**
However in my test case I see several problems (see one output attached, but as it's a multi thread problem it will be different for each execution):
[tests1.txt](https://github.com/codingo/Interlace/files/4803431/tests1.txt)
`grep "10\.10\.10\.1" tests1.txt `
10.10.10.1 1
10.10.10.1 2
10.10.10.1 3
10.10.10.1 4
10.10.10.1 5
10.10.10.1 6
10.10.10.1 7
10.10.10.1 9
10.10.10.1 8

8 comes before 9.

`grep "10\.10\.10\.7" tests1.txt `
10.10.10.7 1
10.10.10.7 2
10.10.10.7 3
10.10.10.7 5
10.10.10.7 4
10.10.10.7 6
10.10.10.7 8
10.10.10.7 7
10.10.10.7 9

5 comes before 4, and 8 comes before 7.

Across other tests, I also found 3 coming before 2, which means even in the first block you can have troubles.

Unfortunately I haven't the skills nor the time to debug this at the moment. I wish I could have helped. 
I think a workaround is to launch different interlace from a bash script for the sequence orders, but it's less powerful than what we could do with this great feature.

Btw, many thanks for this great tool, it's really awesome!

**Comment by xYantix** [comment]
I have just tried to reproduce the issue but things appear to be working as intended on my Macbook. Will try again from a Kali VM if I get a chance. 

<img width="608" alt="Screen Shot 2020-06-22 at 6 24 39 pm" src="https://user-images.githubusercontent.com/3001014/85265471-a9daf200-b4b5-11ea-9e3d-466ac9cf1ab0.png">


```
grep "10\.10\.10\.1" tests1.txt                                                      
10.10.10.1 1
10.10.10.1 2
10.10.10.1 3
10.10.10.1 4
10.10.10.1 5
10.10.10.1 6
10.10.10.1 7
10.10.10.1 8
10.10.10.1 9
```

**Comment by flawseeker** [comment]
Hi,

Did you look at the results for all IPs? It doesn't happen for all of them.

**Comment by prodigysml** [comment]
Hi @flawseeker, I've been trying to reproduce this for a while, but have been unable to. We appreciate that you
