### ISSUE TITLE
Interlace not executing command associated with -c flag

### ISSUE THREAD

**Issue by tarunkant** [codingo/Interlace#104]
```bash
$ interlace -tL target.txt -threads 3 -c "echo 'Scanning _target_ Now'" -v
=====================================================
Interlace v1.8.0	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
[20:46:03] [THREAD] [echo 'Scanning https://pandao.ru/js/jquery-3.2.1.min.js Now'] Added to Queue 
[20:46:03] [THREAD] [echo 'Scanning https://pandao.ru/gtm.js Now'] Added to Queue 
[20:46:03] [THREAD] [echo 'Scanning https://pandao.ru/js/jquery.magnific-popup.min.js Now'] Added to Queue 
[20:46:03] [THREAD] [echo 'Scanning https://pandao.ru/js/jquery.min.js Now'] Added to Queue 
Generated 4 commands in total
Repeat set to 1
 75%|████████████████████████████████▎          | 3/4 [00:00<00:00, 311.06it/s]
```
where `target.txt` contains:
```
https://pandao.ru/gtm.js
https://pandao.ru/gtm.js
https://pandao.ru/js/jquery-3.2.1.min.js
https://pandao.ru/js/jquery-3.2.1.min.js
https://pandao.ru/js/jquery.magnific-popup.min.js
https://pandao.ru/js/jquery.magnific-popup.min.js
https://pandao.ru/js/jquery.min.js
```
The above command with interlace does not execute the shell command as show in the snippet.

Any help would be appreciated.

Thanks,

**Comment by tarunkant** [comment]
I think the problem is with python3.5.

When I tried with python 3.6 then it worked!

So, should I close this issue?

**Comment by prodigysml** [comment]
Glad to hear that! Yes please!

**Comment by Regala** [comment]
Hello! In my opinion setup.py or some runtime check should warn the user that Interlace is running in a version different from 3.2/3.6 (and hence that the -c flag won't run).

**Comment by Regala** [comment]
Actually this is my result with Python 3.6.0:

![image](https://user-images.githubusercontent.com/1380527/87305021-b3340900-c50d-11ea-9989-0a0185148d1c.png)

(not sure why I did `python setup.py install` from the latest repo and got 1.7.6)

**Comment by Regala** [comment]
And this with Python 3.2:

![image](https://user-images.githubusercontent.com/1380527/87306093-6b15e600-c50f-11ea-978a-9700c12739cc.png)

At this point maybe I'm just doing something wrong? 😅

**Comment by tarunkant** [comment]
Hello @Regala,

Maybe try with the latest python3.6.

Thanks,

**Comment by Regala** [comment]
Yep it does work with 3.6; my environment was incorrectly configured so it was using 3.7 even though it was showing 3.6 :-)

**Comment by prodigysml** [comment]
Hey @Regala,

I've been running interlace on Python 3.7 and it has been running fine. Not too sure what's going on there.

Sajeeb
