### ISSUE TITLE
Exception: No target provided, or empty target list.... while running interlace from script.(example.sh)

### ISSUE THREAD

**Issue by unstabl3** [codingo/Interlace#105]
Hi everyone, this is an amazing tool!!

But it does not work if you call interlace from a bash script,
 Following is the command I have added in my script. (example.sh)
`interlace -tL new.txt -c "nmap _target_ -p 80,443 -sV" -threads 5 -v`

Error:
`Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.0', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.8.0-py3.6.egg/Interlace/interlace.py", line 32, in main
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.8.0-py3.6.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.8.0-py3.6.egg/Interlace/lib/core/input.py", line 273, in process_commands
Exception: No target provided, or empty target list`

The same above command works fine if you execute normally! (without script)

where new.txt
```
google.com
facebook.com
github.com
```

I have the latest version of Interlace installed with python 3.6+ on ubuntu.

Any help would be appreciated.

Take care

**Comment by unstabl3** [comment]
I just checked that It's working fine in bash script if we give STDIN.
`cat new.txt | interlace -c "your command" -v -threads 5`

Any workaround for this if we want to give targets list as arguments?

Thanks

**Comment by prodigysml** [comment]
Hey @unstabl3! So glad to hear that you like the software! Unfortunately I haven't been able to reproduce your results. I ran the same command (`interlace -tL targets.txt -c "nmap _target_ -p 80,443 -sV" -threads 5 -v`) as a check and below is the output:
![image](https://user-images.githubusercontent.com/16996819/88514053-c1fdde00-d02c-11ea-9be9-158c05e05748.png)

**Comment by prodigysml** [comment]
Closing the ticket for now, but please feel free to reopen it if you can reproduce it again! Thanks for using Interlace! =)
