### ISSUE TITLE
Create checks when using _target_ with -o option

### ISSUE THREAD

**Issue by lyonys** [codingo/Interlace#118]
When using _target_ with -o, if your target list contains special characters like 'https://', it will fail on generating results as `mkdir https://filename` will fail. This will cause the entire job to not create any results.

hosts.txt contents:
```
https://google.com
https://apple.com
```

Command that would cause failture:
 `interlace -tL ./hosts.txt -c "ffuf -ic -c -w /wordlist_all.txt -u _target_/FUZZ -o test/dirbust/_target_fuff" -v`

**Comment by Max-Trouble** [comment]
Run into the same issue but i noticed this specific case you can use _cleantarget_ (-o test/dirbust/_cleantarget_fuff) which removes https:// or http://
Maybe we can add this to the Variable Replacements section in the readme as it is already implemented?

**Comment by prodigysml** [comment]
Closed with #133, thanks to @Max-Trouble!
