### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by prodigysml** [codingo/Interlace#119]
When large input is passed to interlace (like 100k subdomains or a /8 CIDR), interlace will try to perform the operations of replacing the commands, but will fail miserably due to the limited amount of memory and not so great storage method (all in RAM). 

Basically we need a solution which doesn't run out of memory when receiving 100k targets.

**Comment by mzfr** [comment]
Isn't this more like the problem with the system interlace is running on? I mean what if we run interlace on a high RAM, do you still see this issue?

**Comment by prodigysml** [comment]
Depending on the size of the dataset, it will still exist.

**Comment by iambigyandahal** [comment]
I think you are trying to read the input all at once and perform operations at the same time. 
Try this:
You can have all you input in your file, then you read file line by line. You can collect garbage or if its in Python you need not worry about garbage collection while reading file line by line. While reading line by line, you can perform replacing of commands and add it to a new temporary file. Finally at last you can read the final temporary file to perform the operation you want to perform. You may also combine it with threading to perform other operations parallelly.

**Comment by Akash-Hamal** [comment]
Swap memory

**Comment by prodigysml** [comment]
Swap memory temporarily fixes the issue, however not enough for us to be able to say it is properly resolved. All you need is a larger dataset to consume all your swap memory. At the moment, interlace doesn't replace commands in a memory efficient way at all. I believe it creates around (#commands) ^ (#parameters), so this would likely need to store the commands on disk, or something smarter (like maybe a custom generator to create the commands on the fly).

**Comment by vortexau** [comment]
I ran into this issue on my personal workstation and discussed it directly with @prodigysml and @codingo which lead to the creation of this issue - my machine has 32GB RAM and 32GB of Swap memory. Lots of RAM and Swap doesn't resolve the issue for large CIDR ranges.

**Comment by averagesecurityguy** [comment]
I'm taking a look at this and I have a question regarding the method `InputHelper._process_clean_targets`. I don't understand it's purpose since there is no _cleantarget_ variable listed in the documentation. Is it still used? If so, what is its purpose?

**Comment by codingo** [comment]
Ah! That's a documentation miss, but `_cleantarget_` is essentially to be used when writing out files and the like. I have better documentation and a video underway, so this should be corrected soon.

**Comment by denegtheworld** [comment]
Also having a look but cannot reproduce the bug. I tried with an input file of 86000 domain entries running a single ping and it ran just fine. Also tried with outputting the results to a file with '>>' but that seems to be fine also. 

I have tried using nikto to see if there is any correlation with heavier programs but it simply fails when the domain cannot be found (so I guess another bug to add for later)

The only other thing I found was that it takes FOREVER to build the queue and uses 100% CPU of a single core on a multi-core system. So it may be worth looking at threading that process and even looking at a C module. 

@vortexau do you or anyone else have an input file/scenario to share that could help me reproduce this memory bug?

**Comment by JohnEskimSmith** [comment]
I already tweeted(DM) earlier, looked at the source code. What you want - / 8 or 100K - is impossible to implement in this code. You have written your code in such a way that nothing can be fixed. Moreover, you copy target data multiple times into different variables, doubling in places or tripling memory consumption. It is necessary to rewrite everything. Sorry, maybe for the harshness in the assessment. For a example, 
1. input.py - ranges.update([target.strip() for target in target_file if target.strip()]) - first time put into memory all targets
2. InputHelper._pre_process_hosts(ranges, targets, arguments) - second time in memory
3. commands = InputHelper._process_clean_targets(commands, targets) - third time in memory
4. commands = InputHelper._replace_variable_with_commands(commands, "_host_", targets)
everything is based on the fact that all targets are in memory
If you have /8 CIDR targets - 16,777,216 ips, if you convert them to str - 1 str  IP in range 56 - 64 bytes, ok, let it be 60 byte, and 16,777,216 * 60 = 1 006 632 960 byte = 960 MB RAM. :) it is absolutely wrong to put the targets in a list.
You must change the way you set your targets.

**Comment by vortexau** [comment]
@denegtheworld 

`interlace -t 3.104.0.0/14 -c "echo _target_ >> /tmp/targets " -threads 5` was the command I last used to test.

**Comment by JohnEskimSmith** [comment]
P.S. in this situation I see 2 ways.
1 Not the best way, you can think of ip-str as ip-int before starting processes. And when the process starts, you convert the int to a string. But this won't work with hosts (www.blablabla.com)
2. Rewrite the entire code with using- asyncio, asyncio.create_subprocess_exec, aioconsole, aiofiles, asyncio.Queue
a. asyncio.create_subprocess_exec - for create process and read results from stdout process
b. aioconsole, aiofiles - for read from stdin and files with targets
c. asyncio.Queue - for targets and results
earlier I gave a link to an example - concept. https://www.youtube.com/watch?v=duZQ39M0TTc with targets /8

**Comment by denegtheworld** [comment]
@JohnEskimSmith what do you think about a rewrite in C? 

Bracketed queues and pointers may be vital to a desired outcome.

**Comment by JohnEskimSmith** [comment]
> 
> 
> @JohnEskimSmith what do you think about a rewrite in C?
> 
> Bracketed queues and pointers may be vital to a desired outcome.

I think badly about rewriting to C. I know that this can be rewritten to an asynchronous python in 2-3 days. But I do not have such a need, because I have already written this for myself in a limited version: I run and read the result from the masscan, zmap, zgrab2 and my other utils. I'm just giving normal advice: if you want to include a large number of goals, you can't add all targets to a list.

**Comment by whiteroses** [comment]
I've submitted [a PR](https://github.com/codingo/Interlace/pull/121) -- does it solve the problem for you?

**Comment by JohnEskimSmith** [comment]
@whiteroses the direction and use yield looks ok! However, I think that with the asyncio python - it would be great at all. 
P.S. On the other hand, the main thing is that it works :)

**Comment by KarimPwnz** [comment]
I think using a generator is best.

**Comment by whiteroses** [comment]
@JohnEskimSmith I think asyncio might be helpful in other ways, but from my understanding it wouldn't in itself help with this particular memory issue -- as you mentioned before, it's to do with everything being stored in memory as lists.

@vortexau I tested my PR with [your command](https://github.com/codingo/Interlace/issues/119#issuecomment-700466932), and it worked fine on my computer with 8GB memory (and used relatively little of it).

**Comment by prodigysml** [comment]
Fixed by @whiteroses! Thank you! =)
