### ISSUE TITLE
No output saved

### ISSUE THREAD

**Issue by effortlessdevsec** [codingo/Interlace#122]
=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
[09:37:47] [THREAD] [ping pyrus.com] Added to Queue
Generated 1 commands in total

only addedd to queue showing on runing

**Comment by prodigysml** [comment]
hey @effortlessdevsec, can you please provide the command you ran, so we can attempt to reproduce this issue?

**Comment by prodigysml** [comment]
This is stale, so closing the issue. Please feel free to reopen with more details!
