### ISSUE TITLE
failed to detect a valid IP address from

### ISSUE THREAD

**Issue by welltest** [codingo/Interlace#149]
Getting an error

![128460482-579508c9-8e3a-4c58-a82e-8e4340b29364](https://user-images.githubusercontent.com/7748482/129731514-8be7962d-6a11-4451-9c18-080342f9d03e.png)

**Comment by xYantix** [comment]
Can you provide an example of the command you ran as well as an example of the data you were reading IP addresses from?

**Comment by storenth** [comment]
Looks like there are no clear steps, suggest closing as invalid.
