### ISSUE TITLE
`--silent` shows excessive data

### ISSUE THREAD

**Issue by 0xtavian** [codingo/Interlace#152]
Hey @prodigysml, hope you guys are well :)

This bug has been around for a bit, just wanted to document it..

`--silent` doesnt hide some interlace echo's such as `updating: ['']`, `Generated x commands in total` and `Repeat set to x`

How to recreate: 

Create a file with some data and use interlace:

`for i in $(seq 1 5) ; do echo $i ; done | tee myfile.txt && interlace -tL myfile.txt -c "echo _target_ " -threads 5 --silent --no-bar`
```
updating: ['1']
updating: ['2']
updating: ['3']
updating: ['4']
updating: ['5']
3

5

4

Generated 5 commands in total
Repeat set to 1
1

2

```

Expected output 

`for i in $(seq 1 5) ; do echo $i ; done | tee myfile.txt && interlace -tL myfile.txt -c "echo _target_ " -threads 5 --silent --no-bar`
```



3

5

4

1

2

```

**Comment by prodigysml** [comment]
Hey @0xtavian! That's a good point! It definitely shouldn't be printing out if `--silent` is being used. I'll take a look at what we can do.

**Comment by 0xtavian** [comment]
Sorry on the delay @prodigysml. FYI the master repo works great but I’m excited to test your silence of the lambs patch 8). Maybe give me a few more days. Just been incredibly busy lately. Hope you are well! <3

**Comment by 0xtavian** [comment]
Closing this issue since it’s been merged. When I get some time to review the silence of the lambs patch I’ll just comment my feedback in this issue. Thanks again!
