### ISSUE TITLE
need python 3.10 fix

### ISSUE THREAD

**Issue by gprime31** [codingo/Interlace#154]
![2022-01-17_10-13](https://user-images.githubusercontent.com/44535257/149795117-fa4a0507-3704-4dc6-81f7-99c777a4bdbd.png)

**Comment by gprime31** [comment]
![2022-01-17_10-14_1](https://user-images.githubusercontent.com/44535257/149795408-78902814-b2e9-48ad-97d3-834b35f0df33.png)

**Comment by gprime31** [comment]
tmp workaround:

edit:   /usr/lib/python3.10/site-packages/colorclass/codes.py  
change:
from collections import Mapping
to
from collections.abc import Mapping

**Comment by prodigysml** [comment]
Can definitely make a fix for this one, using `sys.version_info`

**Comment by prodigysml** [comment]
I believe this might be because the pip module we use doesn't support python 3.10 yet.

**Comment by gprime31** [comment]
Oh ok, well the fix above works for now, for anyone else using Arch based, or python 3.10.

**Comment by malekmahmed** [comment]
I still have the same issue and I can't apply the fix 
![image](https://user-images.githubusercontent.com/52550328/169679834-7707f7b8-264c-42c6-b6b9-21898ef6d9f1.png)

I tried to edit the "/usr/local/lib/python3.10/dist-packages/colorclass-2.2.0-py3.10.egg/colorclass/codes.py" file but it says file doesn't exist!

**Comment by 0-0eth0** [comment]
> /usr/local/lib/python3.10/dist-packages/colorclass/codex.py  

Try editing here @malekmahmed

**Comment by KickAss101** [comment]
```
alias interlace="python3.9 /opt/interlace/interlace/interlace.py" 
```
It worked on debian testing.
