### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vansh1** [codingo/Interlace#157]
running install
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing manifest file 'Interlace.egg-info/SOURCES.txt'
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/Interlace
creating build/bdist.linux-x86_64/egg/Interlace/lib
creating build/bdist.linux-x86_64/egg/Interlace/lib/core
byte-compiling build/bdist.linux-x86_64/egg/Interlace/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/threader.py to threader.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/output.py to output.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/__version__.py to __version__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/core/input.py to input.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/lib/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/Interlace/interlace.py to interlace.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Interlace.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Removing /usr/lib/python3.8/site-packages/Interlace-1.9.5-py3.8.egg
Copying Interlace-1.9.5-py3.8.egg to /usr/lib/python3.8/site-packages

**Comment by vansh1** [comment]
Command i used python3 setup.py install

**Comment by xYantix** [comment]
@vansh1 what is the actual problem? Did you leave some of the error message out?
