### ISSUE TITLE
Python3.10 Temp Fix.

### ISSUE THREAD

**Issue by gprime31** [codingo/Interlace#167]
in /usr/lib/python3.10/collections/

__init__.py  ---> add   import _collections_abc   and   from collections.abc import Mapping

abc.py ---> add    from _collections_abc import Mapping

then--->  python3 setup.py install

**Comment by Techbrunch** [comment]
I ran into the same issue, @0xtavian you might want to consider using something other than interlace in the future, @six2dez mentionned rush in https://github.com/six2dez/reconftw/issues/561

**Comment by prodigysml** [comment]
I believe this should be fixed now
