### ISSUE TITLE
Support for Python 3.7?

### ISSUE THREAD

**Issue by njfox** [codingo/Interlace#19]
Does this project support Python 3.7? `python setup.py install` is failing for me in a fresh 3.7.1. venv:

```
$ python setup.py install
Running from numpy source directory.
/tmp/easy_install-i32nmnz2/numpy-1.12.0/setup.py:366: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
/tmp/easy_install-i32nmnz2/numpy-1.12.0/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/tmp/easy_install-i32nmnz2/numpy-1.12.0/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  self.calc_info()
/tmp/easy_install-i32nmnz2/numpy-1.12.0/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  self.calc_info()
non-existing path in 'numpy/distutils': 'site.cfg'
/tmp/easy_install-i32nmnz2/numpy-1.12.0/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/tmp/easy_install-i32nmnz2/numpy-1.12.0/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable lf95
Could not locate executable pgfortran
Could not locate executable f90
Could not locate executable f77
Could not locate executable fort
Could not locate executable efort
Could not locate executable efc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pathf95
don't know how to compile Fortran code on platform 'posix'
[...]
```

Thanks!

**Comment by njfox** [comment]
Thanks for the reply. It does look like `setuptools` is installed:

```
$ pip install setuptools
Requirement already satisfied: setuptools in /home/nick/venvs/interlace/lib/python3.7/site-packages (39.0.1)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I upgraded pip and am still getting the same error. Do you have any other ideas as to what it could be?

**Comment by xYantix** [comment]
Make sure you have pip3 installed `apt-get install python3-pip` and then try pip3 install setup-tools.

**Comment by ProDigySML** [comment]
Yes agreed with @xYantix. @njfox please ensure you use pip3. pip3 is the pip installer for python3. pip is the installer for python 2.7. I must say the names get quite confusing! Interlace is compatible with python3 only at the moment. Please do let us know if you have any issues or whether these comments actually resolve the issue! :)

**Comment by njfox** [comment]
This is a fresh python3 venv (created with `python3 -m venv interlace`), so the `pip` is the installer for python3 in this case. The output from the command shows `python3.7` in the path.

**Comment by ProDigySML** [comment]
Apologies, I'm actually quite baffled! Not too sure what the issue is here. @codingo care to chime in?

**Comment by njfox** [comment]
For what it’s worth, I tried in a python3.6 venv on another machine and it installed fine, which is why I’m wondering if the issue could be related to 3.7 specifically. I know a lot of packages broke when 3.7 came out but it’s also possible that it’s unrelated.

**Comment by xYantix** [comment]
I will spin up a VM and do some testing @njfox @ProDigySML .

**Comment by ProDigySML** [comment]
Thanks mate! I'd do the same, but stuck with some other work. Appreciated!

**Comment by codingo** [comment]
@xYantix appreciated! Feel free to reach out on twitter (@codingo_) if I can assist at all.

**Comment by xYantix** [comment]
@njfox The version of Numpy was updated on the 14/1/19 on Pypi.org so can you try modifying the version of setup.py and replace line 39 `'' if num_installed else 'numpy==1.12.0'],` to  `'' if num_installed else 'numpy==1.16.0'],` and then try re-running it with `python3.7 setup.py install` ? My testing with this has been positive.

**Comment by njfox** [comment]
Thanks @xYantix, that did the trick!

**Comment by ProDigySML** [comment]
That's great to hear! Thanks for sorting this out @xYantix ! Hope you like Interlace @njfox. If you have any feedback or feature requests, please do feel free to reach out (Twitter: sml555_)
