### ISSUE TITLE
Add a _proto_ variable

### ISSUE THREAD

**Issue by gehaxelt** [codingo/Interlace#23]
Hey there, 

I would like to suggest adding a `_proto_` variable and an appropriate command line flag for defining multiple protocols (e.g. `--protocols http,https,ftp`). 

The idea here would be to let tools send requests to different URLs/protocols, e.g. `wget` or `curl` instead of simply passing the ports `80,443,21`, which might cause protocol mismatches. 

Cheers,
gehaxelt

**Comment by ProDigySML** [comment]
Hey @gehaxelt,

That's a good idea! Didn't think of that use case. I'll try to add that in soon.

Sajeeb

**Comment by ProDigySML** [comment]
Pushed some code for this @gehaxelt . Hopefully will be what you requested. Thanks for the request btw! Always welcome new feature requests!

**Comment by codingo** [comment]
Closed with #24
