### ISSUE TITLE
--silent should suppress 'THREAD [...] added to queue'

### ISSUE THREAD

**Issue by gehaxelt** [codingo/Interlace#28]
Hi, 

I run interlace on quite a long list of domains and even with `--silent` set, interlace will output the following message:

```
[09:53:28] [THREAD] [*REDACTED*] Added to Queue
```

This simply brings the shell's/tmux's load up and wastes CPU cycles, because it has to print this unnecessary information A LOT of times. I believe that interlace would also perform better if those CPU cycles would not be wasted on those `print` statements.

Therefore, I'd suggest to make interlace completely silent if that option is set. Output from the called programs should still be printed, though. 

Best,
Sebastian

**Comment by codingo** [comment]
Closed with #29
