### ISSUE TITLE
Support for list of target URLs

### ISSUE THREAD

**Issue by njfox** [codingo/Interlace#39]
I've run into a few situations now where I will have a very large list of URL's in the form of `https://<ip>:<port>/` and it'd be nice to be able to feed this list into Interlace and just access each item with the `_target_` variable. Based on my understanding, Interlace only accepts an IP/hostname for the target and a general list of ports and protocols to use for all hosts, which would result in a lot of pointless scanning of services that aren't listening. 

For example, if one out of 1000 hosts has a web server listening on port 8035, there is no way to keep interlace from running the tool against 8035 on all 1,000 hosts. If I have a preformatted list of URLs, I should be able to just feed that in as a target list and have those URLs be passed as-is to Nikto or gobuster.

**Comment by codingo** [comment]
Sorry, can you explain a bit further? As-is the tool will do processing on dot-notation and ranges / CIDR however we provided `--no-cidr` to prevent expansion of ranges, this ticket highlights the need to have a more generic flag to prevent any sort of expansion for other ranges.

That said, I don't think that's what you're saying and you can already do what I believe that you're asking. To elaborate, if you had a list of:

```
https://127.0.0.1:443
https://127.0.0.1:8080
https://192.168.0.1:443
```
And you ran:

```
interlace -tL ./targets.txt -c "nikto --host _target_"
```
Then Interlace could run:

```
nikto --host https://127.0.0.1:443
nikto --host https://127.0.0.1:8080
nikto --host https://192.168.0.1:443
```

Without the need for the `_port_` option. The idea behind `_port_` is to provide future replacements when you need them, it's not required on each command.

Is this essentially what you're asking, or have I missed the mark?

**Comment by njfox** [comment]
Thanks, I misunderstood the usage of `--no-cidr`. Unfortunately it fails now because it seems to be interpreting the slashes in the URL as directories:

```interlace -tL http-services.txt -c "nikto -h _target_ > _output_/_target_-nikto.txt" -o nikto -v --no-cidr

[...]

sh: 1: nikto: not found
sh: 1: cannot create nikto/http://<ip>:443-nikto.txt: Directory nonexistent
```

Maybe it would be possible to URL encode `/` when writing the output file? This is how httpscreenshot does it I believe.
