### ISSUE TITLE
_port_ doesn't seem to convert to a port when passing in a port list

### ISSUE THREAD

**Issue by mrpaulstone** [codingo/Interlace#47]
I ran the script with the settings as described to use nikto and have this error, it seems to not be converting _port_ into the port number;

- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on www.example.com:_port_
---------------------------------------------------------------------------
+ 0 host(s) tested

**Comment by ProDigySML** [comment]
Seems to be working fine for me. 
![image](https://user-images.githubusercontent.com/16996819/59012487-f89df580-887a-11e9-9f85-30f30d974723.png)

Can we please get some more details of the exact command being run and OS details, python details, etc.?

If at all possible, please test this command out too and post the output:
`interlace -t localhost -p 12 -c "nikto -h _target_:_port_"`

Thanks for using interlace!

**Comment by codingo** [comment]
Also can't reproduce on latest master:
```
➜  Interlace git:(master) interlace -t localhost -p 12 -c "nikto -h _target_:_port_"
=====================================================
Interlace v1.5.2	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
[17:09:55] [THREAD] [nikto -h localhost:12] Added to Queue 
  0%|          | 0/1 [00:00<?, ?it/s]- Nikto v2.1.6

100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
```

**Comment by codingo** [comment]
Actualy, I've tested with pL, port list, and it does appear broken there. Updating issue:

```
➜  Interlace git:(master) interlace -t localhost -pL /tmp/ports.txt -c "nikto -h _target_:_port_" 
=====================================================
Interlace v1.5.2	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
[17:10:32] [THREAD] [nikto -h localhost:_port_] Added to Queue 
  0%|          | 0/1 [00:00<?, ?it/s]- Nikto v2.1.6

100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
```

**Comment by mrpaulstone** [comment]
an example command I used was:
interlace -tL targets.txt -o /root/outputfolderhere/ -cL commands.txt -p 443

**Comment by ProDigySML** [comment]
I was not able to reproduce the issue with the following config:
Output:
```
interlace -tL targets.txt -cL commands.txt -p 443
=================================================================================
Interlace v1.5.1	by Michael Skelton (@codingo_) & Sajeeb Lohani (@sml555_)
=================================================================================
[08:40:59] [THREAD] [echo 128.0.0.1:443] Added to Queue 
[08:40:59] [THREAD] [echo 127.0.0.1:443] Added to Queue 
[08:40:59] [THREAD] [echo 127.0.0.1123:443] Added to Queue 
[08:40:59] [THREAD] [echo 128.0.0.1123:443] Added to Queue 
128.0.0.1:443                                                                                                                                                               

127.0.0.1123:443                                                                                                                                                            

127.0.0.1:443                                                                                                                                                               

128.0.0.1123:443                                                                                                                                                            

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 30.16it/s]
```

targets.txt
```
127.0.0.1
128.0.0.1
```

commands.txt
```
echo _target_:_port_
echo _target_123:_port_
```

If you could provide the list of commands and targets that trigger this bug, it would be appreciated.

**Comment by Ready-Hacker-One** [comment]
When adding nmap to the list without the _port_ variable it breaks the _port_ variable for nikto and sslscan. 

nikto --host _target_:_port_ >> _output_/_target_-nikto.txt
sslscan _target_:_port_ >>  _output_/_target_-sslscan.txt
nmap -sV --script=http-methods _target_ >>  _output_/_target_-nmap.txt

**Comment by codingo** [comment]
Thank-you for the extra detail @Ready-Hacker-One. @ProDigySML and I are discussing this and will look into it shortly.
