### ISSUE TITLE
Overwriting files with >

### ISSUE THREAD

**Issue by Ready-Hacker-One** [codingo/Interlace#48]
Don't you need to change this to `>>`  if you supply two ports 80, 443 then the second scan will just over ride the data in the first *.txt and create a new doc. 

"""

Run a List of Commands against Target Hosts
Often with penetration tests there's a list of commands you want to run on nearly every job. Assuming that list includes testssl.sh, nikto, and sslscan, you could save a command list with the following in a file called commands.txt:

nikto --host _target_:_port_ > _output_/_target_-nikto.txt
sslscan _target_:_port_ >  _output_/_target_-sslscan.txt
testssl.sh _target_:_port_ > _output_/_target_-testssl.txt
If you were then given a target, example.com you could run each of these commands against this target using the following:

interlace -t example.com -o ~/Engagements/example/ -cL ./commands.txt -p 80,443
This would then run nikto, sslscan, and testssl.sh for both port 80 and 443 against example.com and save files into your engagements folder.

"""

**Comment by codingo** [comment]
To be fair, these are just readme examples and it's up to the user to build their own test cases. I'd personally use `tee` in these situations, or redirect to another application entirely. Closing this as it's documentation related, but potentially will  change this next time we revisit this with an upcoming feature.
