### ISSUE TITLE
Forward slashes in targets.txt breaks output file functionality

### ISSUE THREAD

**Issue by naterobbified** [codingo/Interlace#63]
Hi,

I'm working with a targets.txt file which includes targets like the following:
http://example2.com
http://example3.com
http://example4.com

When I run the following command:
```
interlace -tL targets.txt -threads 5 -c "python3 dirsearch.py -e php,aspx -u _target_ > /home/_target_-dirsearch.txt" -v --no-cidr
```

It doesn't work, as it attempts to write files with file names like: "http://example2.com/-dirsearch.txt"

As forward slashes aren't allowed in filenames, the command fails. Perhaps i'm overlooking a possible workaround, but any help would be appreciated.

Thanks

**Comment by codingo** [comment]
Nice pickup, I think given we have `_proto_` the solution will be to just strip `http://` and `https://` from targets when they're added to a target file, thoughts?

**Comment by prodigysml** [comment]
This definitely is a bug. Frankly, without context we can't really sanitize a target for the filename. I'll have a chat with @codingo and come up with a solution.

**Comment by prodigysml** [comment]
@naterobbified , I had a quick chat with @codingo , and we decided to add in a new variable named `_cleantarget_` which will clean the target variable for all `/`s. I'll likely tackle this issue very soon. This definitely was an oversight! Good catch mate!

**Comment by naterobbified** [comment]
Sounds good guys, thanks for the quick response! Excited to try out the tool with my workflow.

**Comment by codingo** [comment]
Close with #73
