### ISSUE TITLE
Idea for helpful variable

### ISSUE THREAD

**Issue by astone75** [codingo/Interlace#88]
Hi all and first of all thanks for this amazing tool.

I think it would be super useful to have a new variable like _targetFilename_ that would transform _target_ into a possible filename.
Indeed we often end up with an input target file like
http://target1
https://target2
...
And when we want to write tool output we end up doing something like, for example : 
interlace -tL urls.txt -threads 10 -o test -c 'ffuf -t 20 -w ~/tools/seclists/Discovery/Web-Content/quickhits.txt -u _target_/FUZZ -r -ac -of csv -o _output_/`echo "_target_"|cut -d '/' -f 3`'

If we had a variable _targetFilename_ it would greatly simplify our job instead of having to rely on bash tricks to generate a proper filename. (we could, for example replace all unproper chars in _target_ by underscores).

**Comment by prodigysml** [comment]
Hey @astone75 ! Glad to hear you are finding it useful! I believe we already have this functionality with the cleantarget variable. https://github.com/codingo/Interlace/blob/master/Interlace/lib/core/input.py#L172

Is that what you are looking for, or is it something else? If it is something else, we are definitely keen to implement it!

**Comment by codingo** [comment]
@prodigysml realised we never added `_cleantarget_` to the documentation. Aiming to do that tomorrow.

**Comment by astone75** [comment]
Great, this is exactly what I was looking for, I didn't see it in the doc and thus thought it didn't exist.
After having read at the code I'd just suggest using a more generic "cleaner function" so, for example, something like "https://test.com:8443" would be cleaned to https_test.com_8443 (ie: delete all '/' and replace all [^a-z0-9\-] by ' _') or use something like django slugify to transform the string.

**Comment by prodigysml** [comment]
I like that actually @astone75! Lets keep this issue open and try to make it more general for usage :)
