### ISSUE TITLE
Large list not supporting

### ISSUE THREAD

**Issue by tester65452** [codingo/Interlace#91]
Hi developer,
Interlace is not supporting large number lines worldlist not supporting. Is there any solution for this problem??
Regards
tester65452

**Comment by prodigysml** [comment]
Yeah I ran into this problem too. The reason it is there is Interlace
stores all commands generated in RAM. As a quick fix, your best bet is
splitting the wordlist file and possibly using a bash loop to run it.

I'll try to write a patch soon which creates a tmp file and stores the
commands there (only for things with more than 10k commands). Should at
least get them to run.
