### ISSUE TITLE
Interlace strange behaviour

### ISSUE THREAD

**Issue by doomguy** [codingo/Interlace#95]
Working:
```
interlace -t webscantest.com  -p 80 -threads 1 -c "nikto -port _port_ -host _target_ -Format csv -o test.csv > test.txt"
```

NOT working:
```
interlace -t webscantest.com  -p 80 -threads 1 -c "nikto -port _port_ -host _target_ -Format csv -o test.csv"
```

Any ideas what might be wrong here? Why is it mandatory to redirect output here?

**Comment by prodigysml** [comment]
Hi @doomguy ,

I'm not too sure why that is not working for you. I just tested it out on my own system, which seemed to work: 
```
interlace -t webscantest.com  -p 80 -threads 1 -c "nikto -port _port_ -host _target_ -Format csv -o test.csv"
=====================================================
Interlace v1.7.6	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
[10:36:30] [THREAD] [nikto -port 80 -host webscantest.com -Format csv -o test.csv] Added to Queue 
Generated 1 commands in total
- Nikto v2.1.6                                                                                                                                                                                                       

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.04it/s]
```

Can you give us any more details to try and reproduce the issue?

**Comment by doomguy** [comment]
Hi @prodigysml,

thanks for your feedback.

How long did it take to produce the result? For me, the process will instantly finish and not generate any scan results. If you do the redirect, Interlace will patiently wait until scanning is done, which is expected as far I know.

**Comment by codingo** [comment]
@prodigysml need me to pick this up?

**Comment by prodigysml** [comment]
Yeah sorry, can't get to this for the next couple of weeks.

**Comment by joohoi** [comment]
This is actually a [bug in Python](https://bugs.python.org/issue35182). It seems to get triggered by a child process of `nikto` that closes the stdout pipe. 

I believe this _not_ being strictly nikto specific, but wouldn't think too many programs do that. Unfortunately I don't know of any fix for the issue itself :/

**Comment by joohoi** [comment]
> Unfortunately I don't know of any fix for the issue itself :/

Or well... Interlace could maybe vendorize the fixed `subprocess` module.

**Comment by joohoi** [comment]
Nvm, I think I fixed it.
